name: Build and Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Build and publish nupkg image
    steps:
      - uses: actions/checkout@v1
      - name: build using docker
        run: docker build -t package -e "BUILD_VERSION=${{github.sha}}" -e "NUGET_API_KEY=${{secrets.NUGET_API_KEY}}"
