name: Build and Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Build and publish nupkg image
    steps:
      - uses: actions/checkout@v1
      
      - name: fetch history
        run: git fetch --prune --unshallow
      
      - name: install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
            versionSpec: '5.2.x'
      
      - name: use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.2
      
      - name: build using docker
        run: docker build -t package . --build-arg "BUILD_VERSION=${{ steps.gitversion.outputs.semVer }}"

      - name: debug
        run: echo ${{secrets.NUGET_API_KEY}}
