name: Build and Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: CI/CD Pipeline
    steps:
      - uses: actions/checkout@v2
      
      - name: fetch history
        run: git fetch --prune --unshallow
      
      - name: install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
            versionSpec: '5.2.x'
      
      - name: use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.2
      
      - name: Debug
        run: echo ${{steps.gitversion.outputs.fullSemVer}}

      - name: build using docker
        run: docker build -t ${{ github.sha }} . --build-arg "BUILD_VERSION=${{ steps.gitversion.outputs.fullSemVer }}"
        
      - name: publish nuget package
        run: docker run -e "NUGET_API_KEY=${{secrets.NUGET_API_KEY}}" ${{ github.sha }}
        if: github.ref == 'refs/heads/master'
