name: Build and Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Build and publish nupkg image
    steps:
      - uses: actions/checkout@v1
      - name: build using docker
        run: docker build -t package . --build-arg "BUILD_VERSION=${{github.sha}}"
      - name: debug
        run: echo ${{secrets.NUGET_API_KEY}}
