name: Build package and push
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
          versionSpec: '5.2.x'

      - name: Get Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.2

      - run: echo "NuGet Version = ${{ steps.gitversion.outputs.nuGetVersionV2 }}"

      - name: 
        run: docker build -t ${{ github.sha }} . --build-arg "BUILD_VERSION=${{ steps.gitversion.outputs.nuGetVersionV2 }}"

      - name: run docker image
        run: docker run -e "NUGET_API_KEY=${{secrets.NUGET_API_KEY}}" ${{ github.sha }}
        if: 