name: Build and Publish
on:
  push:
    paths:
      - 'src/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - name: checkout source
        uses: actions/checkout@v2      
      - name: build docker image
        run: docker build -t ${{ github.sha }} . --build-arg "BUILD_VERSION=0.1.${{ github.run_number }}"
      - name: run docker image
        run: docker run -e "NUGET_API_KEY=${{secrets.NUGET_API_KEY}}" ${{ github.sha }}
        if: github.ref == 'refs/heads/master'