name: Build package
on:
  push:
    branches:
      - master
      - 'feature/**'
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build package
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2        

      - name: Check version
        id: version
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
    
      - run: echo Version = ${{ steps.version.outputs.tag_name }}

      - name: Build Docker image
        run: docker build -t ${{ github.sha }} . --build-arg "BUILD_VERSION=${{ steps.version.outputs.tag_name }}"

      # - name: run docker image
      #   run: docker run -e "NUGET_API_KEY=${{secrets.NUGET_API_KEY}}" ${{ github.sha }}
      #   if: github.ref == 'refs/heads/master'