name: Build
on:
  pull_request:
    branches:
      - master
    
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Verify changes
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
            versionSpec: '5.2.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.2

      - name: Build Docker Image
        run: docker build -t ${{ github.sha }} . --build-arg "BUILD_VERSION=${{ steps.gitversion.outputs.nuGetVersionV2 }}"
