name: Pull Request
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Verify changes
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ${{ github.sha }} . --build-arg "BUILD_VERSION=${{ github.run_number }}-${{ github.sha }}"
